name: build

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.5.0
      - uses: AGraber/sampctl-action@v1
        with:
          version: "1.9.1"
      - run: sampctl p build --forceEnsure
      - uses: actions/upload-artifact@v3.1.1
        with:
          name: compiled-amx
          path: gamemodes/ScavengeSurvive.amx
