name: build

on:
  workflow_dispatch:
  schedule:
   # cronjob that triggers every day at 6PM UTC
   - cron: '0 18 * * *'
  #push:
    #branches: ["main"]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AGraber/sampctl-action@v1
        with:
          version: "1.9.1"
      - run: sampctl p build --forceEnsure
      - uses: actions/upload-artifact@v2
        with:
          name: compiled-amx
          path: gamemodes/ScavengeSurvive.amx
