name: Build Release

on:
  workflow_dispatch:
  schedule:
   # cronjob that triggers every day at 6PM UTC
   - cron: '0 18 * * *'
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest
    name: Build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.4.0
        with:
          submodules: recursive

      - name: Setup Go environment
        uses: actions/setup-go@v3.2.1
        with:
          go-version: "^1.13.1"
      - run: env GOOS=windows GOARCH=amd64 go build -o ScavengeSurvive.exe
      - name: Upload compiled runner
        uses: actions/upload-artifact@v3
        with:
            name: compiled-runner
            path: |
             ScavengeSurvive.exe

      - name: Setup sampctl & Build amx
      - uses: AGraber/sampctl-action@v1
        with:
          version: "1.9.1"
      - run: sampctl p build --forceEnsure

      - name: Upload compiled amx
        uses: actions/upload-artifact@v3
        with:
          name: compiled-amx
          path: gamemodes/ScavengeSurvive.amx
