name: runner

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - uses: actions/setup-go@v3.3.0
        with:
          go-version: "^1.13.1"
          check-latest: true
          cache: true
      - run: env GOOS=windows GOARCH=amd64 go build -o ScavengeSurvive.exe
      - run: env GOOS=linux GOARCH=amd64 go build -o ScavengeSurvive
      - uses: actions/upload-artifact@v3.1.0
        with:
          name: runner
          path: |
            ScavengeSurvive.exe
            ScavengeSurvive
